
package com.naruto.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 05 15:12:14 CST 2019
 * Generated source version: 2.1.3
 * 
 */
 
public class InquiryRiskAmlBorrInfoSrvWs_InquiryRiskAmlBorrInfoSrvWsImplPort_Server{

    protected InquiryRiskAmlBorrInfoSrvWs_InquiryRiskAmlBorrInfoSrvWsImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new InquiryRiskAmlBorrInfoSrvWsImpl();
        String address = "http://localhost:8081/ws_cxf_server_v1.0/InquiryRiskAmlBorrInfoSrvWs";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new InquiryRiskAmlBorrInfoSrvWs_InquiryRiskAmlBorrInfoSrvWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
