package com.naruto.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 05 15:12:14 CST 2019
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/", name = "InquiryRiskAmlBorrInfoSrvWs")
@XmlSeeAlso({ObjectFactory.class})
public interface InquiryRiskAmlBorrInfoSrvWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "inquiryRiskAmlBorrInfo", targetNamespace = "http://queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/", className = "com.naruto.cxf.queryRiskAmlBorrInfo.InquiryRiskAmlBorrInfo")
    @ResponseWrapper(localName = "inquiryRiskAmlBorrInfoResponse", targetNamespace = "http://queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/", className = "com.naruto.cxf.queryRiskAmlBorrInfo.InquiryRiskAmlBorrInfoResponse")
    @WebMethod
    public com.naruto.cxf.OutputCollection inquiryRiskAmlBorrInfo(
            @WebParam(name = "MsgHeader", targetNamespace = "")
                    com.naruto.cxf.MsgHeader msgHeader,
            @WebParam(name = "InputCollection", targetNamespace = "")
                    com.naruto.cxf.InputCollection inputCollection
    );
}
