
package com.naruto.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 05 15:12:14 CST 2019
 * Generated source version: 2.1.3
 * 
 */

public final class InquiryRiskAmlBorrInfoSrvWs_InquiryRiskAmlBorrInfoSrvWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/", "InquiryRiskAmlBorrInfoSrvWsImplService");

    private InquiryRiskAmlBorrInfoSrvWs_InquiryRiskAmlBorrInfoSrvWsImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = InquiryRiskAmlBorrInfoSrvWsImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InquiryRiskAmlBorrInfoSrvWsImplService ss = new InquiryRiskAmlBorrInfoSrvWsImplService(wsdlURL, SERVICE_NAME);
        InquiryRiskAmlBorrInfoSrvWs port = ss.getInquiryRiskAmlBorrInfoSrvWsImplPort();  
        
        {
        System.out.println("Invoking inquiryRiskAmlBorrInfo...");
        com.naruto.cxf.MsgHeader _inquiryRiskAmlBorrInfo_msgHeader = null;
        com.naruto.cxf.InputCollection _inquiryRiskAmlBorrInfo_inputCollection = null;
        com.naruto.cxf.OutputCollection _inquiryRiskAmlBorrInfo__return = port.inquiryRiskAmlBorrInfo(_inquiryRiskAmlBorrInfo_msgHeader, _inquiryRiskAmlBorrInfo_inputCollection);
        System.out.println("inquiryRiskAmlBorrInfo.result=" + _inquiryRiskAmlBorrInfo__return);


        }

        System.exit(0);
    }

}
