
/*
 * 
 */

package com.naruto.cxf;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 05 15:12:14 CST 2019
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "InquiryRiskAmlBorrInfoSrvWsImplService", 
                  wsdlLocation = "http://192.168.32.59:7040/ws_server//InquiryRiskAmlBorrInfoSrvWs?wsdl",
                  targetNamespace = "http://impl.queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/") 
public class InquiryRiskAmlBorrInfoSrvWsImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/", "InquiryRiskAmlBorrInfoSrvWsImplService");
    public final static QName InquiryRiskAmlBorrInfoSrvWsImplPort = new QName("http://impl.queryRiskAmlBorrInfo.risk.inquiry.ws.pccw.com/", "InquiryRiskAmlBorrInfoSrvWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.32.59:7040/ws_server//InquiryRiskAmlBorrInfoSrvWs?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/E:/risk.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InquiryRiskAmlBorrInfoSrvWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InquiryRiskAmlBorrInfoSrvWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InquiryRiskAmlBorrInfoSrvWsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns InquiryRiskAmlBorrInfoSrvWs
     */
    @WebEndpoint(name = "InquiryRiskAmlBorrInfoSrvWsImplPort")
    public InquiryRiskAmlBorrInfoSrvWs getInquiryRiskAmlBorrInfoSrvWsImplPort() {
        return super.getPort(InquiryRiskAmlBorrInfoSrvWsImplPort, InquiryRiskAmlBorrInfoSrvWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InquiryRiskAmlBorrInfoSrvWs
     */
    @WebEndpoint(name = "InquiryRiskAmlBorrInfoSrvWsImplPort")
    public InquiryRiskAmlBorrInfoSrvWs getInquiryRiskAmlBorrInfoSrvWsImplPort(WebServiceFeature... features) {
        return super.getPort(InquiryRiskAmlBorrInfoSrvWsImplPort, InquiryRiskAmlBorrInfoSrvWs.class, features);
    }

}
